services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mon_projet.settings
      - key: SECRET_KEY
        value: 18112023
      - key: DEBUG
        value: False
