services:
  - type: web
    name: django-backend
    env: python
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mon_projet.settings
      - key: SECRET_KEY
        value: 18112023
      - key: DEBUG
        value: False
